In [1]:
# this enable automatic reloading of libraries
%load_ext autoreload
%autoreload 2

from clib.bellhop import *
import numpy as np
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings(action='ignore')
from matplotlib.animation import FuncAnimation

---
---
# Pour 1 profil

In [4]:
#### Normal one
s = bellhop({'gs': {'datadir': '/home/datawork-lops-osi/jgula/NESED/', \
                    'file':10, 'itime':10, 'lon': -66.6, 'lat': 36., \
                    'plot_map': False, 'contour':False}}, zmax = 4900)

1 grid file found, uses: /home/datawork-lops-osi/jgula/NESED/nesea_grd.nc
-- Grid object
dim lon_rho: 1602  2002
lon_rho min= -72.123, max=-58.273
lat_rho min= 34.123, max=43.734
h min= 20.000, max=5543.070
Uses the following output file: /home/datawork-lops-osi/jgula/NESED/nesed_avg.00260.nc
Uses the following time : 10


In [7]:
### Temperature error of 0.002°C
sT = bellhop({'gs': {'datadir': '/home/datawork-lops-osi/jgula/NESED/', \
                    'file':10, 'itime':10, 'lon': -66.6, 'lat': 36., \
                    'plot_map': False, 'contour':False}}, zmax = 4900)

1 grid file found, uses: /home/datawork-lops-osi/jgula/NESED/nesea_grd.nc
-- Grid object
dim lon_rho: 1602  2002
lon_rho min= -72.123, max=-58.273
lat_rho min= 34.123, max=43.734
h min= 20.000, max=5543.070
Uses the following output file: /home/datawork-lops-osi/jgula/NESED/nesed_avg.00260.nc
Uses the following time : 10


In [6]:
#### Lien entre erreur de conductivité C et salinité SP.
import gsw
gsw.C_from_SP(34.5+3e-4, 10, 250)-gsw.C_from_SP(34.5, 10, 250)
### Conclusion : une erreur de 3e-4 en conductivité revient 
#                à la même erreur en salinité.

0.00029416361580558714

In [8]:
### Salinity error of 0.0003 S/m
sS = bellhop({'gs': {'datadir': '/home/datawork-lops-osi/jgula/NESED/', \
                    'file':10, 'itime':10, 'lon': -66.6, 'lat': 36., \
                    'plot_map': False, 'contour':False}}, zmax = 4900)

1 grid file found, uses: /home/datawork-lops-osi/jgula/NESED/nesea_grd.nc
-- Grid object
dim lon_rho: 1602  2002
lon_rho min= -72.123, max=-58.273
lat_rho min= 34.123, max=43.734
h min= 20.000, max=5543.070
Uses the following output file: /home/datawork-lops-osi/jgula/NESED/nesed_avg.00260.nc
Uses the following time : 10


In [20]:
#### erreur due à une ancienne erreur dans get_soundc() de flow.py
#s.SSP['gs']['c'] - s1.SSP['gs']['c']

array([0.0587472 , 0.05872704, 0.05869153, 0.05865939, 0.05865021,
       0.05863824, 0.05862235, 0.05859937, 0.05857014, 0.05853866,
       0.05852887, 0.05852317, 0.05851981, 0.05851716, 0.05853192,
       0.05856617, 0.05863866, 0.05913394, 0.06043535, 0.06142768,
       0.0615951 , 0.06186714, 0.06271214, 0.06379242, 0.06774813,
       0.07250907, 0.0794546 , 0.08917233, 0.10212006, 0.1204394 ,
       0.1418726 , 0.16045798, 0.17651188, 0.18866984, 0.19523551,
       0.19997681, 0.20225725, 0.20375643, 0.205005  , 0.20649763,
       0.20814917, 0.21022103, 0.21247031, 0.214658  , 0.21705483,
       0.21922026, 0.22095643, 0.222247  , 0.22301058, 0.22424986])

In [13]:
##### erreur due à une erreur de température de 0.002 °C
eT = s.SSP['gs']['c'] - sT.SSP['gs']['c']
eT

array([-0.00548044, -0.00548014, -0.00548002, -0.00547994, -0.0054799 ,
       -0.00547988, -0.00547989, -0.00547991, -0.00547995, -0.00548001,
       -0.00548011, -0.00548028, -0.00548057, -0.00548125, -0.00548204,
       -0.00548339, -0.00548521, -0.00549489, -0.00552568, -0.00557728,
       -0.00561268, -0.00565106, -0.00569661, -0.00574151, -0.00581379,
       -0.00590329, -0.00601221, -0.00615657, -0.006353  , -0.00663972,
       -0.00698868, -0.00734575, -0.00769388, -0.00799226, -0.00818827,
       -0.00833539, -0.00842297, -0.00847926, -0.00852086, -0.00855372,
       -0.00858437, -0.00861907, -0.00865483, -0.00868585, -0.00871382,
       -0.00873035, -0.00873521, -0.00872899, -0.00871057, -0.00870101])

In [14]:
##### erreur due à une erreur de salinité de 0.0003 psu
eS = s.SSP['gs']['c'] - sS.SSP['gs']['c']
eS

array([-0.00033623, -0.00033621, -0.00033619, -0.00033617, -0.00033615,
       -0.00033613, -0.0003361 , -0.00033608, -0.00033605, -0.00033603,
       -0.000336  , -0.00033597, -0.00033594, -0.00033592, -0.00033589,
       -0.00033587, -0.00033585, -0.00033596, -0.00033644, -0.0003373 ,
       -0.00033786, -0.00033848, -0.00033921, -0.00033992, -0.0003411 ,
       -0.00034258, -0.00034441, -0.00034687, -0.00035028, -0.00035534,
       -0.00036154, -0.00036794, -0.0003742 , -0.0003796 , -0.00038318,
       -0.00038591, -0.00038757, -0.00038868, -0.00038954, -0.00039027,
       -0.00039099, -0.00039183, -0.00039273, -0.00039357, -0.00039439,
       -0.00039501, -0.00039541, -0.00039557, -0.00039545, -0.00039549])

In [17]:
### 1 profil
print (np.max(abs(eT)))
print(np.mean(abs(eT)))

0.0087352059456407
0.0067347264863929016


In [18]:
### 1 profil 
print (np.max(abs(eS)))
print(np.mean(abs(eS)))

0.00039556577530674986
0.00035814743318951514


---
---
---
# Pour un champ de célérité (107profils)

In [21]:
#### Normal one
S = bellhop({'gs': {'datadir': '/home/datawork-lops-osi/jgula/NESED/', \
                    'file':10, 'itime':10, 'lon': [-66.6, -66.], 'lat': [36.,36.], \
                    'plot_map': False, 'contour':False}}, zmax = 4900)

1 grid file found, uses: /home/datawork-lops-osi/jgula/NESED/nesea_grd.nc
-- Grid object
dim lon_rho: 1602  2002
lon_rho min= -72.123, max=-58.273
lat_rho min= 34.123, max=43.734
h min= 20.000, max=5543.070
Uses the following output file: /home/datawork-lops-osi/jgula/NESED/nesed_avg.00260.nc
Uses the following time : 10
The transect will contain 107 horizontal points


In [20]:
### Temperature error of 0.002°C
ST = bellhop({'gs': {'datadir': '/home/datawork-lops-osi/jgula/NESED/', \
                    'file':10, 'itime':10, 'lon': [-66.6, -66.], 'lat': [36.,36.], \
                    'plot_map': False, 'contour':False}}, zmax = 4900)

1 grid file found, uses: /home/datawork-lops-osi/jgula/NESED/nesea_grd.nc
-- Grid object
dim lon_rho: 1602  2002
lon_rho min= -72.123, max=-58.273
lat_rho min= 34.123, max=43.734
h min= 20.000, max=5543.070
Uses the following output file: /home/datawork-lops-osi/jgula/NESED/nesed_avg.00260.nc
Uses the following time : 10
The transect will contain 107 horizontal points


In [19]:
### Salinity error of 0.0003 S/m
SS = bellhop({'gs': {'datadir': '/home/datawork-lops-osi/jgula/NESED/', \
                    'file':10, 'itime':10, 'lon': [-66.6, -66.], 'lat': [36.,36.], \
                    'plot_map': False, 'contour':False}}, zmax = 4900)

1 grid file found, uses: /home/datawork-lops-osi/jgula/NESED/nesea_grd.nc
-- Grid object
dim lon_rho: 1602  2002
lon_rho min= -72.123, max=-58.273
lat_rho min= 34.123, max=43.734
h min= 20.000, max=5543.070
Uses the following output file: /home/datawork-lops-osi/jgula/NESED/nesed_avg.00260.nc
Uses the following time : 10
The transect will contain 107 horizontal points


In [22]:
ET = S.SSP['gs']['c'] - ST.SSP['gs']['c']
ET

array([[-0.00548044, -0.00548014, -0.00548002, ..., -0.00872899,
        -0.00871057, -0.00870101],
       [-0.00547964, -0.00547933, -0.00547919, ..., -0.00872898,
        -0.00871082, -0.00870119],
       [-0.00547952, -0.00547922, -0.00547908, ..., -0.00872896,
        -0.00871079, -0.00870109],
       ...,
       [-0.00538462, -0.00538431, -0.00538417, ..., -0.00874655,
        -0.00873496, -0.00870703],
       [-0.00538442, -0.00538411, -0.00538397, ..., -0.00874684,
        -0.0087347 , -0.00870652],
       [-0.00538402, -0.00538372, -0.00538359, ..., -0.00874703,
        -0.00873452, -0.00870614]])

In [23]:
ES = S.SSP['gs']['c'] - SS.SSP['gs']['c']
ES

array([[-0.00033623, -0.00033621, -0.00033619, ..., -0.00039557,
        -0.00039545, -0.00039549],
       [-0.00033621, -0.00033619, -0.00033617, ..., -0.00039557,
        -0.00039545, -0.00039549],
       [-0.00033621, -0.00033619, -0.00033617, ..., -0.00039557,
        -0.00039545, -0.00039549],
       ...,
       [-0.00033456, -0.00033453, -0.00033451, ..., -0.00039594,
        -0.00039597, -0.00039562],
       [-0.00033455, -0.00033453, -0.00033451, ..., -0.00039594,
        -0.00039597, -0.00039561],
       [-0.00033455, -0.00033452, -0.0003345 , ..., -0.00039595,
        -0.00039596, -0.0003956 ]])

In [24]:
### 107 profils
print (np.max(abs(ET)))
print(np.mean(abs(ET)))

0.008756061601843612
0.006696193521712583


In [25]:
## 107 profils
print (np.max(abs(ES)))
print(np.mean(abs(ES)))

0.0003959963748911832
0.0003574711691533883
